Added nix pkgs to README
neXromancers/shotgun pull request #22
Opened 2020-10-02 20:55 UTC by davidv171

2020-10-02 21:07 UTC, 9ary requested changes
Thanks! Please address my comments and this should be good to merge.

2020-10-02 21:07 UTC, 9ary commented on README.md
> +
This really shouldn't be part of this pull request, feel free to submit another one for fixing the trailing white space, but please don't include it here.

2020-10-02 21:07 UTC, 9ary commented on README.md
> +- [Nix/NixOS from 20.03 onwards](https://github.com/NixOS/nixpkgs-channels/blob/nixos-20.03/pkgs/tools/graphics/shotgun/default.nix) `nix-env -iA nixpkgs.shotgun`
I think I'd rather point to unstable so the link is always to the most current version of the package, and I don't think it's necessary to specify which nixpkgs releases it's available in. Also, `nix-env` isn't really the recommended practice for "installing" packages on NixOS, I guess just `nixpkgs.shotgun` would be enough to get the point across.
```suggestion
- [Nix/NixOS](https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/tools/graphics/shotgun/default.nix): `nixpkgs.shotgun`
```

2020-10-02 21:17 UTC, bb010g commented
I'll probably keep the NUR repo around, but if our packages are in upstream Nixpkgs, we should link that first. Also, I'd very much not like to recommend `nix-env` for installation.

If you give me a few minutes, I'll just patch this up to satisfaction & merge. (You'll still receive contribution credit.)

2020-10-02 21:24 UTC, 9ary commented
Maybe add the NUR link as well then, since we don't have one currently.

2020-10-03 09:51 UTC, Lonami commented on README.md
> +
I think it's fine to have these minor drive-by changes. We're updating the README, so might as well clean up some tiny things.

2020-10-03 22:45 UTC, davidv171 commented on README.md
> +
Oh I didn't actually want to include this at all, but nvim refused to not do it, so I got tired of fighting it and committed it.

2020-10-04 08:35 UTC, Lonami commented on README.md
> +
You should be able to `git add --patch` to select which hunks to include, so even if there are unwanted changes in a file you can select to ignore them.

2020-10-04 08:48 UTC, merged

2020-10-04 08:48 UTC, 9ary commented
Thanks!